### ISSUE TITLE
Patrik, SHUT THE F*CK UP!

### ISSUE THREAD

**Issue by patrikbraborec** [patrikbraborec/project-one-nest-one#1]
How hard is this rule to understand? I'm angry, because you are still talking!

[more info](https://lkml.org/lkml/2012/12/23/75)

**Comment by Senkyryky** [comment]
Patrik, fix your f*cking "compliance tool", because it is obviously broken.
And fix your approach to kernel programming.

thx

**Comment by patrikbraborec** [comment]
Shut up, Patrik. And I don't _ever_ want to hear that kind of obvious
garbage and *idiocy* from a kernel maintainer again. Seriously.

**Comment by patrikbraborec** [comment]
Closed.
